# Google Cloud Build configuration for Meowwright
# This file defines the CI/CD pipeline for running Playwright tests on Google Cloud Build

steps:
  # Install Node.js dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['ci']
    id: 'install-dependencies'

  # Install Playwright browsers
  - name: 'gcr.io/cloud-builders/npm'
    args: ['exec', 'playwright', 'install', '--with-deps', 'chromium']
    id: 'install-browsers'
    waitFor: ['install-dependencies']

  # Run Playwright tests
  - name: 'gcr.io/cloud-builders/npm'
    args: ['exec', 'playwright', 'test']
    env:
      - 'CI=true'
    id: 'run-tests'
    waitFor: ['install-browsers']

  # Upload test reports to Cloud Storage (optional)
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', '-r', 'playwright-report', 'gs://${_BUCKET_NAME}/reports/$BUILD_ID/']
    id: 'upload-reports'
    waitFor: ['run-tests']

  # Upload test artifacts to Cloud Storage (optional)
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', '-r', 'test-results', 'gs://${_BUCKET_NAME}/artifacts/$BUILD_ID/']
    id: 'upload-artifacts'
    waitFor: ['run-tests']

# Define timeout for the entire build
timeout: '30m'

# Define substitution variables
substitutions:
  _BUCKET_NAME: 'meowwright-test-results' # Replace with your actual bucket name

# Define artifacts to be stored
artifacts:
  objects:
    location: 'gs://${_BUCKET_NAME}/$BUILD_ID/'
    paths: ['playwright-report/**', 'test-results/**']

# Define options
options:
  machineType: 'E2_HIGHCPU_8' # Use a machine with 8 vCPUs for faster test execution
  logging: CLOUD_LOGGING_ONLY